apiVersion: v1
kind: ConfigMap
metadata:
  name: ds389-config
data:
{{- range $path, $_ :=  .Files.Glob  "config/*.ldiff" }}
  {{- printf "%s: |- " (base $path) | nindent 2 }}
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}