---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds389.fullname" . }}
  labels:
    {{- include "ds389.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - appProtocol: {{ $key }}
      name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
    {{- end }}
  selector:
    {{- include "ds389.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds389.fullname" . }}-lb
  labels:
    {{- include "ds389.labels" . | nindent 4 }}
spec:
  ports:
  {{- range $key, $value := .Values.service.ports }}
  - appProtocol: ldap
    name: {{ $key }}
    port: {{ $value.port }}
    protocol: TCP
    targetPort: {{ $value.targetPort }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: {{ include "ds389.fullname" . }}
  type: LoadBalancer
