---
# Namespace для изоляции ресурсов 389ds кластера
# Эквивалент Docker: изоляция контейнеров в отдельной сети
apiVersion: v1
kind: Namespace
metadata:
  name: artldap
  labels:
    name: artldap
    purpose: ldap-cluster
